name: "Wasif Malik"
description: ""

#url: "http://localhost:4000"
url: "http://wasifmalik.com"
baseurl:

bio_title: Hi, my name is Wasif.
bio_desc: I am a developer originally from Pakistan and currently living in Berlin. I love free software! With this blog, I want to prove to the world that I can also write long and boring blog posts. If for some reason you find me interesting, and would like to talk, please get in touch via <a href="http://twitter.com/wmalik">twitter</a>.

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true
